version: "3.9"
services:

  # DO NOT USE IN PRODUCTION DUE TO EXPOSED SOCKET IN THE CONTAINER
  proxy:
    container_name: traefik
    image: traefik:brie # the brie tag refers to v2.4
    restart: unless-stopped
    healthcheck:
      test: "curl --silent --fail --show-error http://localhost:8082/ping/ || exit 1"
      interval:     3s
      timeout:      3s
      retries:      20
      start_period: 20s
    command:
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      - --entrypoints.http.address=:80
      - --entryPoints.ping.address=:8082
      - --api=true
      - --api.insecure=true
      - --log=true
      - --log.level=DEBUG
      - --ping=true
      - --accessLog=true
      - --accessLog.filePath=/var/log/traefik_access.log
      - --accessLog.bufferingSize=100
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=local-dev
    networks:
      - local-dev
    ports:
      - "80:80"
      - "8080:8080"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: "Host(`traefik.localhost`)"
      traefik.http.routers.api.entrypoints: "http"
      traefik.http.routers.api.service: "api@internal"

  whoami:
    image: "nginx:alpine"
    container_name: "simple-service"
    networks:
      - local-dev
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.rule: "Host(`whoami.localhost`)"
      traefik.http.routers.whoami.entrypoints: "http"

networks:
  local-dev:
